IOSD/Algo

Linear_Search.cpp
Added Linear_search.cpp File in C++
Fixes #
ADDED LINEAR SEARCH ALGO. IN C++ LANGUAGE.
FILE INCLUDES FUNCTION & PROGRAM.
-NONE
=> Added Linear Search

Binary_Search.cpp
Fixes #
ADDED BINARY SEARCH ALGO. IN C++ LANGUAGE.
FILE INCLUDES FUNCTION & PROGRAM.
-NONE
=> Added Binary Searching

Bubble_Sort.cpp
Fixes #
ADDED BUBBLE SORT ALGORITHM IN C++ LANGUAGE.
FILE INCLUDES FUNCTION & PROGRAM.
-NONE
=> Added Bubble Sort

sel_sort.cpp
SELECTION SORT IN C++.
ADDED A PROGRAM IN C++ HAVING SELECTION SORT.
=> Adding Selection Sort

ins_sort.cpp
Added ins_sort.cpp In C++ having Insertion Sort
Added insertion Sort
=> Added Insertion Sort

insertion_sort.cpp, selection_sort.cpp
Fixes #3f73ff6
- [ *] I have read the [Contribution Guide] and my PR follows them.
- [* ] My branch is up-to-date with the master branch.
- [ *] I have added tests that prove my fix is effective or that my feature works
- [ *] I have added necessary documentation (if appropriate)
- [ *] The contents added are completelt original and have no copyright issues.
This is the source code of selection sort. 
-No intial changes , program coded by me only.
-
-
=> Added Selection Sort

merge_sort.cpp
Added merge_sort.cpp in C++ language.
added merge sort in C++ language.
=> Added Merge Sort

stack.cpp
Fixes #6eae9fd
- [ *] I have read the [Contribution Guide] and my PR follows them.
- [ *] My branch is up-to-date with the master branch.
- [ *] I have added tests that prove my fix is effective or that my feature works
- [ *] I have added necessary documentation (if appropriate)
- [ *] The contents added are completelt original and have no copyright issues.
It contains the source code of stack pushing and poping elementsin C++.
-Created by me only , no as such changes 
-
-
-
=> Stack Code Added

Binary_Search.cpp, Bubble_Sort.cpp, Linear_Search.cpp, ins_sort.cpp
Added Missing delete operator used to deinitialize pointer.
used delete operator to deinitialize pointers.
=> Delete operator Added

queue.cpp, stack.cpp
b8fb3e0
Fixes #
- [ *] I have read the [Contribution Guide] and my PR follows them.
- [ *] My branch is up-to-date with the master branch.
- [ *] I have added tests that prove my fix is effective or that my feature works
- [ *] I have added necessary documentation (if appropriate)
- [ *] The contents added are completelt original and have no copyright issues.
It contains source code of Queue , adding and deleting elements in queue in C++
-Created by me only , no changes as such
-
-
=> Queue Code Added

bubblesort_recursion.cpp
Fixes #
it gives the method to sort an array using bubble sort with recursion
CREATED by me only.no changes required as such.
-
-
-
=> added bubble sort using recursion

linked.cpp
a23ea12
Fixes #a23ea12
- [ *] I have read the [Contribution Guide] and my PR follows them.
- [ *] My branch is up-to-date with the master branch.
- [ *] I have added tests that prove my fix is effective or that my feature works
- [ *] I have added necessary documentation (if appropriate)
- [ *] The contents added are completelt original and have no copyright issues.
It contains source code of insertion of elements in linked list in C++
-Created by me only , no changes as such
-
-
=> Linked List Insertion Added

merge_2arrays.cpp
C++
Fixes #
program to merge one array into another one.
created by me and no changes required.
-
-
-
=> program to merge 2 arrays

sieve of eratosthenes.cpp
=> sieve of eratosthenes-for finding prime numbers

between two sets.cpp
=> between two sets

cats and mouse.cpp, sock merchant.cpp
=> cats and mouse

selectionsort.java
=> selectionsort.java

electronics shop.cpp
=> electronics shop

General/Modular Exponentation.cpp, General/Segmented Sieve.cpp
Added Modular Exponentation x**y%p
=> Added Modular Exponentation

General/Prime Factors.py
=> Python Prime Factors

coinchange.cpp, dist_from_source.cpp
=> Coin Change DP problem

tbbfs.cpp
=> SPOJ - TDBFS problem

Games/Maze.cpp
=> Added Maze in Games

BitManipulation.md, General/Day Of Week.c, General/linearRecurssion.cpp, Search/Ternary_Search.cpp, Solutions to Known Problems/CODECHEF_DIVSUBS, Solutions to Known Problems/SPOJ_FAVDICE.cpp, Solutions to Known Problems/SPOJ_FIBOSUM.cpp
=> Added Sakamoto's algorithm to find the day of week & also added Ternary Search

Strings/Anagram.java
Add the string anagram algorithm
=> feat: add string related algorithms

snackdown2019-OnlineQualifier/Chef and Semi-Primes.md
=> Create Chef and Semi-Primes.md

snackdown2019-OnlineQualifier/Chef and Semi-Primes.md
=> Update Chef and Semi-Primes.md

snackdown2019-OnlineQualifier/Spread the Word.md
=> Create Spread the Word.md

snackdown2019-OnlineQualifier/Chef and Operations.md
=> Create Chef and Operations.md

Greedy/Greedy.java
=> feat: add algorithms for greedy

Data Structures/BinaryTree.java
=> feat: add binary tree in java

Data Structures/VectorErase.cpp, Data Structures/VectorSort.cpp
Fixes #
- [*] I have read the [Contribution Guide] and my PR follows them.
- [*] My branch is up-to-date with the master branch.
- [*] I have added tests that prove my fix is effective or that my feature works
- [*] I have added necessary documentation (if appropriate)
- [*] The contents added are complete. lt original and have no copyright issues.
Adds two new files to Data Structures directory: (1) Vector sort, and (2) Vector erase. Implemented on C++.
=> Files added to Algo/Data Structures

Sorting/bubble-sort.py
Adds Bubble Sort algorithm implemented in Python programming language.
- New file that contains the Bubble Sort algorithm.
=> Bubble Sort algorithm in Python

General/Prime.cpp
=> Check Prime.cpp

README 2019 Hactoberfest 2019.md
=> Updates to new developers for hacktoberfest 2019
